# —————————— Profile —————————— #
# language
language: en
# avatar
avatar: img/assets/cat.png # 头像
# author
author: Leo
# signature
signature: 前进或后退都在我怀里
# SNS
social:
  email: freeleox@foxmail.com
  github: //github.com/freeleox
  weibo: //weibo.com
  facebook: //facebook.com
  twitter: //twitter.com/freeleoxxx
  rss: /atom.xml

# —————————— Site —————————— #
# title of the site
SEO_title: Leo Shaw's Blog
# main title
main_title: Leo's Blog
# subtitle
subtitle: Follow your heart
# site haeder image
site_header_image: '/img/intro/moon.jpg'
# post haeder image
post_header_image: '/img/intro/bear-bg.png'
# about image
about_header_image: 

# —————————— Indivdual —————————— #
# Miscelaneous
favicon: /img/assets/favicon.ico
# —————————— Option —————————— #
# truncate length of abstracts in index page (the default is 300, there will be no abstruct if you input 0)
truncate_length: 
# intro height (the default is 70 percents of the screen)
intro_height: 70
# enable toc
toc: true
# word count & reading time
reading_info: false
# access statistics
count:
  # enable analytics
  # true or flase
  busuanzi: true
  # baidu code
  baidu: 
# Time
# you can modify the timestamp format.
date_format: YYYY-MM-DD
# display created time.
display_created: true
# display updated time, if the post dose not define 'updated', the system modification time will be displayed.
display_updated: false
# copyright
copyright:
  enable: true
  # https://creativecommons.org/
  license: All articles in this blog are licensed under <a rel="license" href="https://creativecommons.org/licenses/by-nc-nd/3.0">CC BY-NC-SA 3.0</a> unless stating additionally.
# comment
comment:
  # Livere  site: https://livere.com/
  livere_uid:
  # Disqus  site: https://disqus.com/
  disqus_shortname: 
  # Changyan  site: http://changyan.kuaizhan.com/
  changyan_appid: 
  changyan_conf: 
  # Gitment  site: https://github.com/imsun/gitment/
  gitment_owner:
  gitment_repo:
  gitment_client_id:
  gitment_client_secret:

# —————————— Others —————————— #
# main menu navigation
menu:
  Home: /
  About: /about/
  Archives: /archives/
  Tags: /tags/
# stylesheets loaded in the <head>
stylesheets:
- /css/style.css?v=2018.7.9
- /css/animation.css?v=2018.7.9
# scripts loaded in the end of the body
scripts:
- /js/main.js?v=2018.7.9
- /js/love.js?v=2018.7.9
search:
  path: search.xml
  field: post
  format: html
  limit: 10000